INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Mr. Chocolate', 12, "M", "Dark Brown", "Fire", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Rowdy', 5, "M", "Light Brown", "Fire", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Tabitha', 7, "F", "Black", "Fire", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Sergeant Brown', 11, "M", "Azure", "Fire", 0)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Melissa', 15, "F", "Black", "Fire", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Grinch', 33, "M", "White", "Fire", 0)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Wendy',23, "F", "White", "Fire", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES (NULL, 3, "F", "Red", "Fire", 1)
